
+ 专业书籍 [14/14]
  1. [X] Unix环境高级编程

	 从事Unix环境应用编程的技术人员至少应该读一遍此书。
	 这本书介绍了Unix应用编程的各个方面，包括：文件、进程、线程、进程IPC以及Socket编程。

	 本书的开始篇章便介绍了POSIX标准，POSIX是由IEEE协会制定的一系列可移植的操作系统接口标准。
	 之后的章节读起来像是对POSIX标准的一次深入解读，确实可以这么理解，但此书的目的绝不在解读标准。
	 本书以Unix环境应用编程的相关知识点为线索划分章节，
	 各章节或以操作接口(API)，或从相关概念和技术入手全面而深入的介绍了操作系统各模块的应用编程入口。

  2. [X] Unix网络编程(卷1：套接字联网API)

  3. [X] Unix网络编程(卷2：进程间通信)

  4. [X] Linux系统编程

	 从文件、进程、内存、信号等方面详细论述了Linux应用编程接口，
	 且在某些章节对编程接口的内核实现有浅略的论述。
	 这本书同《APUE》有很大程度的重叠，如果已阅读过《APUE》，可略过此书。

  5. [X] TCP/IP详解(卷1：协议)

  6. [X] 游戏引擎架构

	 介绍了从游戏团队，到开发工具，到软件工程，再到3D图形渲染等各个方面跟游戏开发相关的内容。
	 这种大而全的书对于资深的从业人员来讲不是那么适用，不过对于初出茅庐的新手而言却是大有裨益。

  7. [X] 图灵的秘密

  8. [X] 实用Common Lisp编程

  9. [X] 3D数学基础

  10. [X] 自动机理论、语言和计算机导论

  11. [X] The compact Org-mode Guide

	  Emacs Org-Mode 模式介绍。

  12. [X] 简明 Python 教程

  13. [X] 跟我一起写Makefile

  14. [X] ARQ协议 (Automatic Repeat reQuest)

	  ARQ协议(或称ARQ算法)是一套可靠传输机制。目前有三种较常见的ARQ算法：

	  1. Stop and Wait

		 该算法只允许发送端最多发送一条未经确认的分组数据。这有点类似TCP处理小数据分组的Nagle算法。
		 这种算法的优点是简单易实现，缺点是不能有效的利用网络带宽，传输效率也比较低下。

	  2. Go Back N

		 该算法允许同时发送N条未经确认的分组数据。

	  3. Selective Repeat

* TODO 读书计划 [0%]

** TODO C程序设计语言
** TODO Linux Kernel Development [/]
** TODO 算法导论 [/]
** TODO 编译原理(龙书) [/]
