@startuml TemplateMethod

class AbstractClass {
    +TemplateMethod()
    #PrimitiveOperationA()
    #PrimitiveOperationB()
}

class ConcreteClass {
    #PrimitiveOperationA()
    #PrimitiveOperationB()
}

AbstractClass <|-- ConcreteClass

@enduml